
package com.theteam.bpmn.engine.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS", targetNamespace = "http://ws.engine.bpmn.theteam.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.engine.bpmn.theteam.com/WS/getHelloRequest", output = "http://ws.engine.bpmn.theteam.com/WS/getHelloResponse")
    public String getHello(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.engine.bpmn.theteam.com/WS/getResponseWithNameRequest", output = "http://ws.engine.bpmn.theteam.com/WS/getResponseWithNameResponse")
    public String getResponseWithName(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
