/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.theteam.bpmn.design;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application {
    
    public String getGreeting() {
        return "Hello world.";
    }

    @Override
    public void start(Stage stage) {
        String javaVersion = System.getProperty("java.version");
        String javafxVersion = System.getProperty("javafx.version");
        Label l = new Label("Hello, JavaFX " + javafxVersion + ", running on Java " + javaVersion + ".");
        Scene scene = new Scene(new StackPane(l), 640, 480);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) throws Exception{

        launch();

        System.out.println(new App().getGreeting());
        
        TestXML t = new TestXML();
        
        t.start();
    }
}
